// Comprehensive crop database with 50 crops - Updated March 2026
import type { CropData } from '../types/crop';

export const cropDatabase: CropData[] = [
  // 1. Paddy
  { id: 'paddy_001', cropNameEN: 'Paddy', cropNameTA: 'நெல்', phRange: { min: 5.5, max: 6.5 }, soilTypeTA: 'களிமண் வண்டல்', soilTypeEN: 'Clay Loam / Alluvial', tempRange: { min: 21, max: 37 }, waterRequirement: 1200, fertilizerRequirementsEN: 'NPK 150:50:50 + Zinc Sulfate (25kg/ha)', fertilizerActionTA: 'NPK + துத்தநாக சல்பேட் (ZnSO4)', primaryFertilizer: '150:50:50', micronutrients: 'Zinc Sulfate (25kg/ha) + Gypsum (500kg/ha)' },
  // 2. Sorghum
  { id: 'sorghum_001', cropNameEN: 'Sorghum', cropNameTA: 'சோளம்', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'கரிசல் / செம்மண்', soilTypeEN: 'Black / Red Soil', tempRange: { min: 26, max: 32 }, waterRequirement: 475, fertilizerRequirementsEN: 'NPK 80:40:40 + Azospirillum', fertilizerActionTA: 'NPK (80:40:40)', primaryFertilizer: '80:40:40', micronutrients: 'Azospirillum (2kg/ha)' },
  // 3. Pearl Millet
  { id: 'pearlmillet_001', cropNameEN: 'Pearl Millet', cropNameTA: 'கம்பு', phRange: { min: 6.5, max: 7.5 }, soilTypeTA: 'மணற்பாங்கான மண்', soilTypeEN: 'Sandy Loam', tempRange: { min: 28, max: 35 }, waterRequirement: 300, fertilizerRequirementsEN: 'NPK 70:35:35 + Iron Sulfate spray', fertilizerActionTA: 'இரும்பு சல்பேட் (FeSO4) தெளிக்க', primaryFertilizer: '70:35:35', micronutrients: 'Iron Sulfate (FeSO4) foliar spray' },
  // 4. Finger Millet
  { id: 'fingermillet_001', cropNameEN: 'Finger Millet', cropNameTA: 'ராகி', phRange: { min: 5.5, max: 7.0 }, soilTypeTA: 'செம்மண் வண்டல்', soilTypeEN: 'Sandy Loam / Red Soil', tempRange: { min: 25, max: 30 }, waterRequirement: 330, fertilizerRequirementsEN: 'NPK 60:30:30 + Farm Yard Manure', fertilizerActionTA: 'தொழு உரம் + NPK (60:30:30)', primaryFertilizer: '60:30:30', micronutrients: 'Farm Yard Manure (12.5 t/ha)' },
  // 5. Maize
  { id: 'maize_001', cropNameEN: 'Maize', cropNameTA: 'மக்காச்சோளம்', phRange: { min: 6.0, max: 7.2 }, soilTypeTA: 'வடிகால் செம்மண்', soilTypeEN: 'Well-drained Red Loam', tempRange: { min: 18, max: 27 }, waterRequirement: 550, fertilizerRequirementsEN: 'NPK 135:62.5:50 + Zinc Sulfate (37.5kg)', fertilizerActionTA: 'துத்தநாக சல்பேட் (50kg/ha)', primaryFertilizer: '135:62.5:50', micronutrients: 'Zinc Sulfate (37.5kg/ha for hybrids)' },
  // 6. Blackgram
  { id: 'blackgram_001', cropNameEN: 'Blackgram', cropNameTA: 'உளுந்து', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'வண்டல் மண்', soilTypeEN: 'Loamy / Alluvial', tempRange: { min: 25, max: 35 }, waterRequirement: 290, fertilizerRequirementsEN: 'NPK 25:50:25 + 2% DAP Foliar Spray', fertilizerActionTA: '2% DAP இலைவழி தெளிப்பு', primaryFertilizer: '25:50:25', micronutrients: '2% DAP Foliar Spray + Pulse Wonder' },
  // 7. Greengram
  { id: 'greengram_001', cropNameEN: 'Greengram', cropNameTA: 'பாசிப்பயறு', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'வண்டல் மண்', soilTypeEN: 'Alluvial Soil', tempRange: { min: 25, max: 35 }, waterRequirement: 275, fertilizerRequirementsEN: 'NPK 25:50:25 + TNAU Pulse Wonder', fertilizerActionTA: 'TNAU பல்ஸ் வொண்டர்', primaryFertilizer: '25:50:25', micronutrients: 'TNAU Pulse Wonder (5kg/ha)' },
  // 8. Redgram
  { id: 'redgram_001', cropNameEN: 'Redgram', cropNameTA: 'துவரை', phRange: { min: 6.5, max: 8.0 }, soilTypeTA: 'செம்மண்', soilTypeEN: 'Red / Sandy Loam', tempRange: { min: 18, max: 30 }, waterRequirement: 550, fertilizerRequirementsEN: 'NPK 25:50:25 + DAP Spray', fertilizerActionTA: 'NPK (25:50:25)', primaryFertilizer: '25:50:25', micronutrients: 'DAP (Diammonium Phosphate) spray' },
  // 9. Groundnut
  { id: 'groundnut_001', cropNameEN: 'Groundnut', cropNameTA: 'நிலக்கடலை', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'மணற்பாங்கான மண்', soilTypeEN: 'Sandy Red Soil', tempRange: { min: 24, max: 30 }, waterRequirement: 525, fertilizerRequirementsEN: 'NPK 25:50:75 + Gypsum (400kg/ha)', fertilizerActionTA: 'ஜிப்சம் (400kg/ha) + போராக்ஸ்', primaryFertilizer: '25:50:75', micronutrients: 'Gypsum (400kg/ha) + Borax (10kg/ha)' },
  // 10. Sesame
  { id: 'sesame_001', cropNameEN: 'Sesame', cropNameTA: 'எள்', phRange: { min: 5.5, max: 7.5 }, soilTypeTA: 'மணற்பாங்கான மண்', soilTypeEN: 'Sandy Loam', tempRange: { min: 25, max: 30 }, waterRequirement: 175, fertilizerRequirementsEN: 'NPK 35:23:23 + Manganese Sulfate', fertilizerActionTA: 'மாங்கனீசு சல்பேட் (5kg/ha)', primaryFertilizer: '35:23:23', micronutrients: 'Manganese Sulfate (MnSO4) (5kg/ha)' },
  // 11. Cotton
  { id: 'cotton_001', cropNameEN: 'Cotton', cropNameTA: 'பருத்தி', phRange: { min: 6.5, max: 8.5 }, soilTypeTA: 'கரிசல் மண்', soilTypeEN: 'Black Soil (Deep)', tempRange: { min: 21, max: 32 }, waterRequirement: 650, fertilizerRequirementsEN: 'NPK 80:40:40 + Magnesium Sulfate', fertilizerActionTA: 'மெக்னீசியம் சல்பேட் (MgSO4)', primaryFertilizer: '80:40:40', micronutrients: 'Magnesium Sulfate (MgSO4) (20kg/ha)' },
  // 12. Sugarcane
  { id: 'sugarcane_001', cropNameEN: 'Sugarcane', cropNameTA: 'கரும்பு', phRange: { min: 6.5, max: 8.0 }, soilTypeTA: 'களிமண் வண்டல்', soilTypeEN: 'Clay Loam', tempRange: { min: 20, max: 35 }, waterRequirement: 2000, fertilizerRequirementsEN: 'NPK 275:62.5:112.5 + Micronutrients', fertilizerActionTA: 'இரும்பு சல்பேட் + NPK', primaryFertilizer: '275:62.5:112.5', micronutrients: 'Iron + Zinc mixture spray' },
  // 13. Turmeric
  { id: 'turmeric_001', cropNameEN: 'Turmeric', cropNameTA: 'மஞ்சள்', phRange: { min: 5.5, max: 7.5 }, soilTypeTA: 'மணற்பாங்கான மண்', soilTypeEN: 'Sandy Loam', tempRange: { min: 20, max: 30 }, waterRequirement: 1500, fertilizerRequirementsEN: 'NPK 150:60:108 + FeSO4 (100kg/ha)', fertilizerActionTA: 'FeSO4 (100kg/ha) + தொழு உரம்', primaryFertilizer: '150:60:108', micronutrients: 'FeSO4 (100kg/ha) + Zinc Sulfate' },
  // 14. Banana
  { id: 'banana_001', cropNameEN: 'Banana', cropNameTA: 'வாழை', phRange: { min: 6.5, max: 7.5 }, soilTypeTA: 'வண்டல் மண்', soilTypeEN: 'Rich Alluvial', tempRange: { min: 20, max: 30 }, waterRequirement: 1500, fertilizerRequirementsEN: 'NPK 110:35:330 (g/plant) + Potash', fertilizerActionTA: 'அதிக பொட்டாஷ் (Potash) உரம்', primaryFertilizer: '110:35:330', micronutrients: 'Potash-heavy application + Micronutrients' },
  // 15. Tomato
  { id: 'tomato_001', cropNameEN: 'Tomato', cropNameTA: 'தக்காளி', phRange: { min: 6.0, max: 7.0 }, soilTypeTA: 'செம்மண் வண்டல்', soilTypeEN: 'Well-drained Red Loam', tempRange: { min: 18, max: 27 }, waterRequirement: 500, fertilizerRequirementsEN: 'NPK 75:40:25 + Borax (10kg/ha)', fertilizerActionTA: 'போராக்ஸ் (10kg/ha) + NPK', primaryFertilizer: '75:40:25', micronutrients: 'Borax (10kg/ha) + Zinc Sulfate' },
  // 16. Chilli
  { id: 'chilli_001', cropNameEN: 'Chilli', cropNameTA: 'மிளகாய்', phRange: { min: 6.0, max: 7.0 }, soilTypeTA: 'மணல் / கரிசல்', soilTypeEN: 'Sandy Loam / Black', tempRange: { min: 20, max: 30 }, waterRequirement: 450, fertilizerRequirementsEN: 'NPK 30:60:30 + Zinc Sulfate', fertilizerActionTA: 'துத்தநாக சல்பேட் (ZnSO4)', primaryFertilizer: '30:60:30', micronutrients: 'Potassium Sulfate (for fruit quality)' },
  // 17. Onion
  { id: 'onion_001', cropNameEN: 'Onion', cropNameTA: 'வெங்காயம்', phRange: { min: 6.0, max: 7.0 }, soilTypeTA: 'மணற்பாங்கான மண்', soilTypeEN: 'Sandy Loam', tempRange: { min: 15, max: 25 }, waterRequirement: 400, fertilizerRequirementsEN: 'NPK 50:150:75 + Elemental Sulfur', fertilizerActionTA: 'கந்தகம் (Sulphur - 30kg/ha)', primaryFertilizer: '50:150:75', micronutrients: 'Elemental Sulfur (30kg/ha) + ZnSO4' },
  // 18. Brinjal
  { id: 'brinjal_001', cropNameEN: 'Brinjal', cropNameTA: 'கத்தரி', phRange: { min: 5.5, max: 6.8 }, soilTypeTA: 'வண்டல் மண்', soilTypeEN: 'Silt Loam / Alluvial', tempRange: { min: 21, max: 30 }, waterRequirement: 550, fertilizerRequirementsEN: 'NPK 50:50:30 + Phosphobacteria', fertilizerActionTA: 'தொழு உரம் (25t) + NPK', primaryFertilizer: '50:50:30', micronutrients: 'Azospirillum + Phosphobacteria (2kg each)' },
  // 19. Coconut
  { id: 'coconut_001', cropNameEN: 'Coconut', cropNameTA: 'தென்னை', phRange: { min: 5.5, max: 7.5 }, soilTypeTA: 'கடற்கரை மணல்', soilTypeEN: 'Coastal Sandy / Red', tempRange: { min: 20, max: 32 }, waterRequirement: 2000, fertilizerRequirementsEN: 'NPK 560:320:1200 (g/palm) + Tonic', fertilizerActionTA: 'TNAU தென்னை டானிக்', primaryFertilizer: '560:320:1200', micronutrients: 'TNAU Coconut Tonic (200ml/palm)' },
  // 20. Mango
  { id: 'mango_001', cropNameEN: 'Mango', cropNameTA: 'மாம்பழம்', phRange: { min: 5.5, max: 7.5 }, soilTypeTA: 'செம்மண் வண்டல்', soilTypeEN: 'Red / Alluvial Loam', tempRange: { min: 24, max: 30 }, waterRequirement: 700, fertilizerRequirementsEN: 'NPK (1:1:1.5 ratio) + Potash', fertilizerActionTA: 'மரம் ஒன்றுக்கு 1kg பொட்டாஷ்', primaryFertilizer: '1:1:1.5', micronutrients: 'Potash (1kg per tree for bearing trees)' },
  // 21. Bhendi
  { id: 'bhendi_001', cropNameEN: 'Bhendi', cropNameTA: 'வெண்டை', phRange: { min: 6.0, max: 6.8 }, soilTypeTA: 'வண்டல் மண்', soilTypeEN: 'Well-drained Loamy', tempRange: { min: 21, max: 35 }, waterRequirement: 450, fertilizerRequirementsEN: 'NPK 20:50:30 + Urea top dressing', fertilizerActionTA: 'ஆர்கானிக் கம்போஸ்ட் + NPK', primaryFertilizer: '20:50:30', micronutrients: 'Urea top dressing (20kg N)' },
  // 22. Small Millets
  { id: 'smallmillets_001', cropNameEN: 'Small Millets', cropNameTA: 'சிறுதானியம்', phRange: { min: 5.0, max: 7.0 }, soilTypeTA: 'ஏழை மண்', soilTypeEN: 'Red Loam / Laterite', tempRange: { min: 25, max: 32 }, waterRequirement: 250, fertilizerRequirementsEN: 'NPK 40:20:0 + Bio-fertilizers', fertilizerActionTA: 'உயிர் உரங்கள் (Bio-fertilizers)', primaryFertilizer: '40:20:0', micronutrients: 'Bio-fertilizers (Azospirillum)' },
  // 23. Horsegram
  { id: 'horsegram_001', cropNameEN: 'Horsegram', cropNameTA: 'கொள்ளு', phRange: { min: 5.0, max: 7.5 }, soilTypeTA: 'செம்மண் / சரளை', soilTypeEN: 'Red / Poor Laterite', tempRange: { min: 25, max: 32 }, waterRequirement: 225, fertilizerRequirementsEN: 'NPK 12.5:25:0 + Rock Phosphate', fertilizerActionTA: 'ராக் பாஸ்பேட் (Rock Phosphate)', primaryFertilizer: '12.5:25:0', micronutrients: 'Rock Phosphate placement' },
  // 24. Castor
  { id: 'castor_001', cropNameEN: 'Castor', cropNameTA: 'ஆமணக்கு', phRange: { min: 5.0, max: 8.0 }, soilTypeTA: 'செம்மண்', soilTypeEN: 'Red Loamy Soil', tempRange: { min: 20, max: 30 }, waterRequirement: 350, fertilizerRequirementsEN: 'NPK 30:15:15 + Zinc Sulfate', fertilizerActionTA: 'துத்தநாக சல்பேட் (25kg/ha)', primaryFertilizer: '30:15:15', micronutrients: 'Zinc Sulfate (25kg/ha)' },
  // 25. Sunflower
  { id: 'sunflower_001', cropNameEN: 'Sunflower', cropNameTA: 'சூரியகாந்தி', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'கரிசல் மண்', soilTypeEN: 'Black Soil', tempRange: { min: 20, max: 25 }, waterRequirement: 475, fertilizerRequirementsEN: 'NPK 60:90:60 + Borax (10kg/ha)', fertilizerActionTA: 'போராக்ஸ் (10kg/ha)', primaryFertilizer: '60:90:60', micronutrients: 'Borax (10kg/ha) + Sulfur (40kg/ha)' },
  // 26. Grapes
  { id: 'grapes_001', cropNameEN: 'Grapes', cropNameTA: 'திராட்சை', phRange: { min: 6.5, max: 7.5 }, soilTypeTA: 'சரளை மண்', soilTypeEN: 'Gravelly Loam', tempRange: { min: 15, max: 35 }, waterRequirement: 650, fertilizerRequirementsEN: 'NPK 0.5:0.5:1.0 (kg/vine) + Boron', fertilizerActionTA: 'மல்டி-நியூட்ரியண்ட் கலவை', primaryFertilizer: '0.5:0.5:1.0', micronutrients: 'Multi-nutrient mixture (Boron, Zinc, Iron)' },
  // 27. Jasmine
  { id: 'jasmine_001', cropNameEN: 'Jasmine', cropNameTA: 'மல்லிகை', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'வடிகால் செம்மண்', soilTypeEN: 'Well-drained Loam', tempRange: { min: 20, max: 30 }, waterRequirement: 700, fertilizerRequirementsEN: 'NPK 60:120:120 (g/plant) + FeSO4', fertilizerActionTA: 'இரும்பு சல்பேட் தெளிப்பு', primaryFertilizer: '60:120:120', micronutrients: 'FeSO4 + ZnSO4 foliar mixture' },
  // 28. Acid Lime
  { id: 'acidlime_001', cropNameEN: 'Acid Lime', cropNameTA: 'எலுமிச்சை', phRange: { min: 5.5, max: 7.5 }, soilTypeTA: 'வண்டல் மண்', soilTypeEN: 'Alluvial Soil', tempRange: { min: 20, max: 30 }, waterRequirement: 900, fertilizerRequirementsEN: 'NPK 600:200:300 (g/tree) + Copper Sulfate', fertilizerActionTA: 'மயில் துத்தம் (Copper Sulfate)', primaryFertilizer: '600:200:300', micronutrients: 'Copper Sulfate (CuSO4) spray' },
  // 29. Papaya
  { id: 'papaya_001', cropNameEN: 'Papaya', cropNameTA: 'பப்பாளி', phRange: { min: 6.0, max: 6.5 }, soilTypeTA: 'மணற்பாங்கான மண்', soilTypeEN: 'Sandy Loam', tempRange: { min: 25, max: 30 }, waterRequirement: 900, fertilizerRequirementsEN: 'NPK 50:50:50 (g/plant) + Borax', fertilizerActionTA: '0.1% போராக்ஸ் தெளிப்பு', primaryFertilizer: '50:50:50', micronutrients: '0.1% Borax spray for fruit setting' },
  // 30. Moringa
  { id: 'moringa_001', cropNameEN: 'Moringa', cropNameTA: 'முருங்கை', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'மணற்பாங்கு', soilTypeEN: 'Sandy Soil', tempRange: { min: 25, max: 35 }, waterRequirement: 350, fertilizerRequirementsEN: 'NPK 45:15:30 (g/pit) + Micronutrients', fertilizerActionTA: 'NPK + நுண்ஊட்டச்சத்து கலவை', primaryFertilizer: '45:15:30', micronutrients: 'NPK + Micronutrient mixture' },
  // 31. Tapioca
  { id: 'tapioca_001', cropNameEN: 'Tapioca', cropNameTA: 'மரவள்ளி', phRange: { min: 5.0, max: 7.0 }, soilTypeTA: 'செம்மண்', soilTypeEN: 'Red Sandy Soil', tempRange: { min: 25, max: 30 }, waterRequirement: 450, fertilizerRequirementsEN: 'NPK 50:50:120 + High Potash', fertilizerActionTA: 'பொட்டாஷ் (120kg/ha)', primaryFertilizer: '50:50:120', micronutrients: 'Potash (120kg/ha) for tuber growth' },
  // 32. Ginger
  { id: 'ginger_001', cropNameEN: 'Ginger', cropNameTA: 'இஞ்சி', phRange: { min: 5.5, max: 6.5 }, soilTypeTA: 'களிமண் மணல்', soilTypeEN: 'Clayey Sand / Loam', tempRange: { min: 20, max: 30 }, waterRequirement: 1500, fertilizerRequirementsEN: 'NPK 75:50:50 + Farm Yard Manure', fertilizerActionTA: 'தொழு உரம் (30t)', primaryFertilizer: '75:50:50', micronutrients: 'Farm Yard Manure (30 t/ha)' },
  // 33. Cardamom
  { id: 'cardamom_001', cropNameEN: 'Cardamom', cropNameTA: 'ஏலக்காய்', phRange: { min: 5.0, max: 6.5 }, soilTypeTA: 'காடு மண்', soilTypeEN: 'Forest Humus Loam', tempRange: { min: 10, max: 25 }, waterRequirement: 2500, fertilizerRequirementsEN: 'NPK 75:75:150 + Magnesium Sulfate', fertilizerActionTA: 'மெக்னீசியம் சல்பேட்', primaryFertilizer: '75:75:150', micronutrients: 'Magnesium Sulfate (MgSO4)' },
  // 34. Pepper
  { id: 'pepper_001', cropNameEN: 'Pepper', cropNameTA: 'மிளகு', phRange: { min: 5.0, max: 6.0 }, soilTypeTA: 'மலை மண்', soilTypeEN: 'Forest Loamy Soil', tempRange: { min: 10, max: 30 }, waterRequirement: 2000, fertilizerRequirementsEN: 'NPK 100:40:140 (g/vine) + Dolomite', fertilizerActionTA: 'டோலமைட் (Dolomite) இடவும்', primaryFertilizer: '100:40:140', micronutrients: 'Dolomite (for pH correction)' },
  // 35. Cocoa
  { id: 'cocoa_001', cropNameEN: 'Cocoa', cropNameTA: 'கோகோ', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'மலை மண்', soilTypeEN: 'Forest / Hill Soil', tempRange: { min: 15, max: 35 }, waterRequirement: 1500, fertilizerRequirementsEN: 'NPK 100:40:140 (g/tree) + MOP Splits', fertilizerActionTA: 'NPK (100:40:140)', primaryFertilizer: '100:40:140', micronutrients: 'Urea + Super Phosphate + MOP splits' },
  // 36. Pumpkin
  { id: 'pumpkin_001', cropNameEN: 'Pumpkin', cropNameTA: 'பூசணி', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'மணற்பாங்கு', soilTypeEN: 'Sandy Loam', tempRange: { min: 24, max: 32 }, waterRequirement: 500, fertilizerRequirementsEN: 'NPK 60:30:30 + Organic Compost', fertilizerActionTA: 'ஆர்கானிக் கம்போஸ்ட்', primaryFertilizer: '60:30:30', micronutrients: 'Organic Compost + NPK' },
  // 37. Watermelon
  { id: 'watermelon_001', cropNameEN: 'Watermelon', cropNameTA: 'தர்பூசணி', phRange: { min: 6.0, max: 7.0 }, soilTypeTA: 'மணல் மண்', soilTypeEN: 'Sandy Soil', tempRange: { min: 24, max: 35 }, waterRequirement: 350, fertilizerRequirementsEN: 'NPK 55:55:55 + Calcium Nitrate', fertilizerActionTA: 'கால்சியம் நைட்ரேட்', primaryFertilizer: '55:55:55', micronutrients: 'Calcium Nitrate (for sweetness/firmness)' },
  // 38. Garlic
  { id: 'garlic_001', cropNameEN: 'Garlic', cropNameTA: 'பூண்டு', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'மலை மண்', soilTypeEN: 'Hill Soil / Loam', tempRange: { min: 12, max: 20 }, waterRequirement: 450, fertilizerRequirementsEN: 'NPK 75:75:75 + Sulfur', fertilizerActionTA: 'கந்தகம் (Sulphur) இடவும்', primaryFertilizer: '75:75:75', micronutrients: 'Sulfur (S) for pungent aroma' },
  // 39. Arecanut
  { id: 'arecanut_001', cropNameEN: 'Arecanut', cropNameTA: 'பாக்கு', phRange: { min: 5.0, max: 8.0 }, soilTypeTA: 'ஆழமான மண்', soilTypeEN: 'Deep Clay Loam', tempRange: { min: 15, max: 35 }, waterRequirement: 1500, fertilizerRequirementsEN: 'NPK 100:40:150 (g/palm) + Green Leaf', fertilizerActionTA: 'ஆர்கானிக் மல்ச்சிங்', primaryFertilizer: '100:40:150', micronutrients: 'Green Leaf Manure (15kg/palm)' },
  // 40. Potato
  { id: 'potato_001', cropNameEN: 'Potato', cropNameTA: 'உருளை', phRange: { min: 4.8, max: 5.4 }, soilTypeTA: 'அமில மண்', soilTypeEN: 'Acidic Silt Loam', tempRange: { min: 15, max: 20 }, waterRequirement: 550, fertilizerRequirementsEN: 'NPK 120:240:120 + Sulfur', fertilizerActionTA: 'கந்தகம் (40kg/ha)', primaryFertilizer: '120:240:120', micronutrients: 'Magnesium and Sulfur supplements' },
  // 41. Carrot
  { id: 'carrot_001', cropNameEN: 'Carrot', cropNameTA: 'கேரட்', phRange: { min: 5.5, max: 6.5 }, soilTypeTA: 'ஆழமான மணல்', soilTypeEN: 'Deep Sandy Soil', tempRange: { min: 10, max: 18 }, waterRequirement: 450, fertilizerRequirementsEN: 'NPK 90:90:90 + Potash', fertilizerActionTA: 'பொட்டாஷ் (60kg/ha)', primaryFertilizer: '90:90:90', micronutrients: 'Potassium (Potash) for root color' },
  // 42. Beetroot
  { id: 'beetroot_001', cropNameEN: 'Beetroot', cropNameTA: 'பீட்ரூட்', phRange: { min: 6.0, max: 7.0 }, soilTypeTA: 'மணற்பாங்கு', soilTypeEN: 'Sandy Loam', tempRange: { min: 15, max: 22 }, waterRequirement: 350, fertilizerRequirementsEN: 'NPK 60:160:100 + Borax', fertilizerActionTA: 'போரான் (Boron) இடவும்', primaryFertilizer: '60:160:100', micronutrients: 'Boron (Borax) to prevent heart rot' },
  // 43. Cabbage
  { id: 'cabbage_001', cropNameEN: 'Cabbage', cropNameTA: 'முட்டைக்கோஸ்', phRange: { min: 5.5, max: 6.5 }, soilTypeTA: 'களிமண் வண்டல்', soilTypeEN: 'Clay Loam', tempRange: { min: 15, max: 20 }, waterRequirement: 450, fertilizerRequirementsEN: 'NPK 90:90:90 + Sodium Molybdate', fertilizerActionTA: 'போராக்ஸ் + சோடியம் மாலிப்டேட்', primaryFertilizer: '90:90:90', micronutrients: 'Sodium Molybdate (prevent whiptail)' },
  // 44. Coffee
  { id: 'coffee_001', cropNameEN: 'Coffee', cropNameTA: 'காபி', phRange: { min: 5.0, max: 6.5 }, soilTypeTA: 'மலை மண்', soilTypeEN: 'Forest Loam / Laterite', tempRange: { min: 15, max: 25 }, waterRequirement: 1500, fertilizerRequirementsEN: 'NPK 160:120:160 + Lime', fertilizerActionTA: 'சுண்ணாம்பு (Lime)', primaryFertilizer: '160:120:160', micronutrients: 'Lime (Calcium Carbonate) for soil pH' },
  // 45. Tea
  { id: 'tea_001', cropNameEN: 'Tea', cropNameTA: 'தேயிலை', phRange: { min: 4.5, max: 5.5 }, soilTypeTA: 'அமில மலை மண்', soilTypeEN: 'Acidic Hill Soil', tempRange: { min: 20, max: 27 }, waterRequirement: 1500, fertilizerRequirementsEN: 'NPK 120:90:90 + Aluminum Sulfate', fertilizerActionTA: 'அலுமினியம் சல்பேட்', primaryFertilizer: '120:90:90', micronutrients: 'Aluminum Sulfate (if pH > 5.5)' },
  // 46. Guava
  { id: 'guava_001', cropNameEN: 'Guava', cropNameTA: 'கொய்யா', phRange: { min: 4.5, max: 8.2 }, soilTypeTA: 'மணற்பாங்கு', soilTypeEN: 'Sandy / Red Loam', tempRange: { min: 20, max: 30 }, waterRequirement: 700, fertilizerRequirementsEN: 'NPK 600:300:300 (g/tree) + Zinc', fertilizerActionTA: 'துத்தநாகம் + போரான் தெளிப்பு', primaryFertilizer: '600:300:300', micronutrients: 'Zinc + Boron foliar spray' },
  // 47. Sapota
  { id: 'sapota_001', cropNameEN: 'Sapota', cropNameTA: 'சப்போட்டா', phRange: { min: 6.0, max: 8.0 }, soilTypeTA: 'மணற்பாங்கு', soilTypeEN: 'Sandy Loam', tempRange: { min: 20, max: 35 }, waterRequirement: 900, fertilizerRequirementsEN: 'NPK (5:5:10 ratio) + Organic Manure', fertilizerActionTA: 'ஆர்கானிக் உரம் + NPK', primaryFertilizer: '600:450:450', micronutrients: 'Organic manure + NPK (5:5:10 ratio)' },
  // 48. Curry Leaf
  { id: 'curryleaf_001', cropNameEN: 'Curry Leaf', cropNameTA: 'கறிவேப்பிலை', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'செம்மண்', soilTypeEN: 'Red Loam', tempRange: { min: 20, max: 35 }, waterRequirement: 500, fertilizerRequirementsEN: 'NPK 150:25:50 + Iron Sulfate', fertilizerActionTA: 'இரும்பு சல்பேட் தெளிப்பு', primaryFertilizer: '150:25:50', micronutrients: 'Iron Sulfate spray for leaf health' },
  // 49. Rose
  { id: 'rose_001', cropNameEN: 'Rose', cropNameTA: 'ரோஜா', phRange: { min: 6.0, max: 7.0 }, soilTypeTA: 'செம்மண்', soilTypeEN: 'Red Loamy Soil', tempRange: { min: 15, max: 25 }, waterRequirement: 700, fertilizerRequirementsEN: 'NPK 10:20:20 (g/plant) + Mulch', fertilizerActionTA: 'ஆர்கானிக் மல்ச்சிங்', primaryFertilizer: '10:20:20', micronutrients: 'Organic Mulching + Micronutrients' },
  // 50. Crossandra
  { id: 'crossandra_001', cropNameEN: 'Crossandra', cropNameTA: 'கனகாம்பரம்', phRange: { min: 6.0, max: 7.5 }, soilTypeTA: 'செம்மண்', soilTypeEN: 'Red Loam', tempRange: { min: 20, max: 35 }, waterRequirement: 600, fertilizerRequirementsEN: 'NPK 15:60:30 + Zinc Sulfate', fertilizerActionTA: 'துத்தநாகம் இடவும்', primaryFertilizer: '15:60:30', micronutrients: 'Zinc Sulfate application' }
];
